language: cpp

compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpng-dev gcc-4.8 g++-4.8
  - curl -OL http://security.ubuntu.com/ubuntu/pool/universe/c/cpputest/libcpputest-dev_3.4-3_amd64.deb
  - sudo dpkg -i libcpputest-dev_3.4-3_amd64.deb
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - mkdir build
  - cd build
  - cmake ..

script:
  - make debug
  - make
  - make check

branches:
  only:
    - master
